[app]
name = "demo"
host = "0.0.0.0"
port = "8050"
key  = "this is your app key"

[mysql]
host = "127.0.0.1"
port = "3307"
username = "root"
password = "123456"
database = "mydb"

[log]
level = "debug"
dir = "logs"
format = "text"
to = "stdout"